import type { MechanismDefinition } from '../types/index.ts';

/** Diagnosis-to-mechanism matrix — machine-readable registry (spec §15, §17). */
export const MECHANISM_REGISTRY: MechanismDefinition[] = [
  {
    id: 'normal',
    displayName: 'Normal sinus rhythm',
    category: 'Normal',
    defaultSeverity: 0,
    defaultExpression: 1,
    modifiers: {},
    interactionTags: [],
    validationCases: ['normal_sinus'],
  },
  {
    id: 'stemi_ant',
    displayName: 'Anterior STEMI',
    category: 'Ischemia',
    defaultSeverity: 1,
    defaultExpression: 0.9,
    modifiers: { ischemia_severity: 1, ischemia_transmurality: 1 },
    ischemiaTerritories: [{ territory: 'LAD', degree: 1 }],
    interactionTags: ['ischemia'],
    validationCases: ['anterior_infarction'],
  },
  {
    id: 'stemi_inf',
    displayName: 'Inferior STEMI',
    category: 'Ischemia',
    defaultSeverity: 1,
    defaultExpression: 0.9,
    modifiers: { ischemia_severity: 1, ischemia_transmurality: 1 },
    ischemiaTerritories: [{ territory: 'RCA', degree: 1 }],
    interactionTags: ['ischemia'],
    validationCases: ['inferior_infarction'],
  },
  {
    id: 'stemi_lat',
    displayName: 'Lateral STEMI',
    category: 'Ischemia',
    defaultSeverity: 1,
    defaultExpression: 0.9,
    modifiers: { ischemia_severity: 1, ischemia_transmurality: 1 },
    ischemiaTerritories: [{ territory: 'LCx', degree: 1 }],
    interactionTags: ['ischemia'],
    validationCases: ['lateral_infarction'],
  },
  {
    id: 'nstemi',
    displayName: 'NSTEMI',
    category: 'Ischemia',
    defaultSeverity: 0.9,
    defaultExpression: 0.85,
    modifiers: { ischemia_severity: 0.9, ischemia_transmurality: 0.3 },
    ischemiaTerritories: [
      { territory: 'anterior', degree: 0.9, layer: 'endo' },
      { territory: 'lateral', degree: 0.9, layer: 'endo' },
      { territory: 'inferior', degree: 0.6, layer: 'endo' },
      { territory: 'septal', degree: 0.6, layer: 'endo' },
    ],
    interactionTags: ['ischemia'],
    validationCases: ['nstemi'],
  },
  {
    id: 'wellens',
    displayName: 'Wellens syndrome',
    category: 'Ischemia',
    defaultSeverity: 0.7,
    defaultExpression: 0.6,
    modifiers: { ischemia_severity: 0.3, global_apd_offset_ms: -40 },
    ischemiaTerritories: [{ territory: 'LAD', degree: 0.3, layer: 'epi' }],
    interactionTags: ['ischemia', 'reperfusion'],
    validationCases: ['wellens'],
  },
  {
    id: 'wpw_a',
    displayName: 'WPW type A',
    category: 'Pre-excitation',
    defaultSeverity: 0.8,
    defaultExpression: 0.85,
    modifiers: { accessory_pathway_preexcitation_fraction: 0.9, accessory_pathway_delay_ms: 5, av_node_delay_ms: 25 },
    interactionTags: ['preexcitation'],
    validationCases: ['wpw'],
  },
  {
    id: 'brugada1',
    displayName: 'Brugada type 1',
    category: 'Channelopathy',
    defaultSeverity: 0.8,
    defaultExpression: 0.75,
    modifiers: { rvot_electrical_abnormality: 0.8, sodium_channel_availability: 0.6, repolarization_dispersion: 0.5 },
    interactionTags: ['brugada', 'channelopathy'],
    validationCases: ['brugada_fever'],
  },
  {
    id: 'lqts',
    displayName: 'Long QT syndrome',
    category: 'Channelopathy',
    defaultSeverity: 0.7,
    defaultExpression: 0.8,
    modifiers: { global_apd_offset_ms: 90, repolarization_dispersion: 0.4 },
    interactionTags: ['channelopathy', 'long_qt'],
    validationCases: ['long_qt_torsades'],
  },
  {
    id: 'af',
    displayName: 'Atrial fibrillation',
    category: 'Arrhythmia',
    defaultSeverity: 0.8,
    defaultExpression: 0.9,
    modifiers: { af_source_activity: 1.35, atrial_mass_scale: 1.15 },
    rhythmMode: 'af',
    interactionTags: ['arrhythmia', 'af'],
    validationCases: ['af_pulse_deficit'],
  },
  {
    id: 'aflutter',
    displayName: 'Atrial flutter',
    category: 'Arrhythmia',
    defaultSeverity: 0.7,
    defaultExpression: 0.85,
    modifiers: { flutter_cycle_length_ms: 200 },
    rhythmMode: 'aflutter',
    interactionTags: ['arrhythmia', 'flutter'],
    validationCases: ['atrial_flutter'],
  },
  {
    id: 'wenckebach',
    displayName: 'Wenckebach (2° AVB I)',
    category: 'Arrhythmia',
    defaultSeverity: 0.5,
    defaultExpression: 0.7,
    modifiers: { av_node_delay_ms: 40 },
    params: { avConduction: 0.55 },
    rhythmMode: 'wenckebach',
    interactionTags: ['av_block'],
    validationCases: ['wenckebach'],
  },
  {
    id: 'mobitz2',
    displayName: 'Mobitz II (2° AVB II)',
    category: 'Arrhythmia',
    defaultSeverity: 0.6,
    defaultExpression: 0.75,
    modifiers: { av_node_block_fraction: 0.3 },
    params: { avConduction: 0.4 },
    rhythmMode: 'mobitz2',
    interactionTags: ['av_block'],
    validationCases: ['mobitz2'],
  },
  {
    id: 'chb',
    displayName: 'Complete heart block',
    category: 'Arrhythmia',
    defaultSeverity: 0.9,
    defaultExpression: 0.95,
    modifiers: { av_node_block_fraction: 1 },
    params: { avConduction: 0 },
    rhythmMode: 'chb',
    hrOverride: 40,
    interactionTags: ['av_block'],
    validationCases: ['complete_av_block'],
  },
  {
    id: 'vt',
    displayName: 'Ventricular tachycardia',
    category: 'Arrhythmia',
    defaultSeverity: 0.9,
    defaultExpression: 0.95,
    modifiers: { vt_origin_region: 'lv_inferior' },
    rhythmMode: 'vt',
    hrOverride: 150,
    interactionTags: ['vt'],
    validationCases: ['monomorphic_vt'],
  },
  {
    id: 'vf',
    displayName: 'Ventricular fibrillation',
    category: 'Arrhythmia',
    defaultSeverity: 1,
    defaultExpression: 1,
    modifiers: { vf_activity: 1.5 },
    rhythmMode: 'vf',
    interactionTags: ['vf'],
    validationCases: ['ventricular_fibrillation'],
  },
  {
    id: 'lvh',
    displayName: 'LV hypertrophy',
    category: 'Hypertrophy',
    defaultSeverity: 0.7,
    defaultExpression: 0.65,
    modifiers: { lv_hypertrophy_scale: 2.0, global_apd_offset_ms: 30, ischemia_severity: 0.2 },
    ischemiaTerritories: [{ territory: 'lateral', degree: 0.3, layer: 'endo' }],
    interactionTags: ['hypertrophy', 'lvh'],
    validationCases: ['lvh'],
  },
  {
    id: 'rvh',
    displayName: 'RV hypertrophy',
    category: 'Hypertrophy',
    defaultSeverity: 0.7,
    defaultExpression: 0.7,
    modifiers: { rv_hypertrophy_scale: 4.0, global_apd_offset_ms: -30 },
    interactionTags: ['hypertrophy', 'rvh'],
    validationCases: ['rvh'],
  },
  {
    id: 'pericarditis',
    displayName: 'Acute pericarditis',
    category: 'Inflammation',
    defaultSeverity: 0.5,
    defaultExpression: 0.6,
    modifiers: { ischemia_severity: 0.42, ischemia_transmurality: 0.8 },
    ischemiaTerritories: [
      { territory: 'anterior', degree: 0.42, layer: 'epi' },
      { territory: 'lateral', degree: 0.42, layer: 'epi' },
      { territory: 'inferior', degree: 0.42, layer: 'epi' },
    ],
    interactionTags: ['inflammation'],
    validationCases: ['pericarditis'],
  },
  {
    id: 'lbbb',
    displayName: 'Left bundle branch block',
    category: 'Conduction',
    defaultSeverity: 0.8,
    defaultExpression: 0.9,
    modifiers: { left_bundle_delay_ms: 120 },
    params: { lbbConduction: 0.12 },
    interactionTags: ['bundle_block', 'lbbb'],
    validationCases: ['lbbb'],
  },
  {
    id: 'rbbb',
    displayName: 'Right bundle branch block',
    category: 'Conduction',
    defaultSeverity: 0.8,
    defaultExpression: 0.9,
    modifiers: { right_bundle_delay_ms: 115 },
    params: { rbbConduction: 0.12 },
    interactionTags: ['bundle_block', 'rbbb'],
    validationCases: ['rbbb'],
  },
  {
    id: 'hyperk_mild',
    displayName: 'Hyperkalaemia (mild, K⁺ ~6)',
    category: 'Electrolyte',
    defaultSeverity: 0.4,
    defaultExpression: 0.5,
    modifiers: { potassium_effect: 0.4, global_apd_offset_ms: -30, global_conduction_scale: 0.85, atrial_mass_scale: 0.55 },
    interactionTags: ['electrolyte', 'hyperkalemia'],
    validationCases: ['hyperkalemia_progression'],
  },
  {
    id: 'hyperk_mod',
    displayName: 'Hyperkalaemia (moderate, K⁺ ~7)',
    category: 'Electrolyte',
    defaultSeverity: 0.6,
    defaultExpression: 0.7,
    modifiers: { potassium_effect: 0.65, global_apd_offset_ms: -55, global_conduction_scale: 0.55, atrial_mass_scale: 0.12, av_node_delay_ms: 40 },
    interactionTags: ['electrolyte', 'hyperkalemia'],
    validationCases: ['hyperkalemia_progression'],
  },
  {
    id: 'hyperk_sev',
    displayName: 'Hyperkalaemia (severe, K⁺ 8+)',
    category: 'Electrolyte',
    defaultSeverity: 0.95,
    defaultExpression: 0.95,
    modifiers: { potassium_effect: 0.95, global_apd_offset_ms: -80, global_conduction_scale: 0.3, atrial_mass_scale: 0, av_node_delay_ms: 60 },
    interactionTags: ['electrolyte', 'hyperkalemia'],
    validationCases: ['hyperkalemia_progression'],
  },
  {
    id: 'pe',
    displayName: 'Pulmonary embolism',
    category: 'Other',
    defaultSeverity: 0.72,
    defaultExpression: 0.55,
    modifiers: { rv_pressure_load: 0.68, rv_hypertrophy_scale: 2.0, ischemia_severity: 0.45 },
    params: { Rpul: 0.35 },
    hrOverride: 110,
    interactionTags: ['pe', 'rv_strain'],
    trajectory: { onsetMs: 120000, riseTimeMs: 60000 },
    validationCases: ['pe_rv_strain', 'pe_no_diagnostic_ecg'],
  },
  {
    id: 'early_repol',
    displayName: 'Early repolarisation',
    category: 'Normal variant',
    defaultSeverity: 0.2,
    defaultExpression: 0.5,
    modifiers: { j_point_shift_mv: 0.15, global_apd_offset_ms: -25 },
    interactionTags: ['normal_variant'],
    validationCases: ['early_repolarization'],
  },
  {
    id: 'p_mitrale',
    displayName: 'Left atrial enlargement',
    category: 'Chamber',
    defaultSeverity: 0.5,
    defaultExpression: 0.6,
    modifiers: { left_atrial_dilation: 0.5, atrial_mass_scale: 1.5, av_node_delay_ms: 25 },
    interactionTags: ['atrial_enlargement'],
    validationCases: ['p_mitrale'],
  },
  {
    id: 'p_pulmonale',
    displayName: 'Right atrial enlargement',
    category: 'Chamber',
    defaultSeverity: 0.5,
    defaultExpression: 0.55,
    modifiers: { right_atrial_dilation: 0.6, atrial_mass_scale: 2.0 },
    interactionTags: ['atrial_enlargement'],
    validationCases: ['pe_p_pulmonale'],
  },
  {
    id: 'digitalis',
    displayName: 'Digitalis effect',
    category: 'Drug effect',
    defaultSeverity: 0.4,
    defaultExpression: 0.5,
    modifiers: { global_apd_offset_ms: -75, ischemia_severity: 0.24 },
    ischemiaTerritories: [
      { territory: 'lateral', degree: 0.24, layer: 'endo' },
      { territory: 'inferior', degree: 0.24, layer: 'endo' },
    ],
    interactionTags: ['drug'],
    validationCases: ['digitalis_effect'],
  },
];

export function getMechanism(id: string): MechanismDefinition | undefined {
  return MECHANISM_REGISTRY.find((m) => m.id === id);
}

export function catalogEntries(): Array<{ id: string; name: string; category: string; description: string }> {
  return MECHANISM_REGISTRY.map((m) => ({
    id: m.id,
    name: m.displayName,
    category: m.category,
    description: `${m.displayName} — mechanism-based simulation`,
  }));
}
